name: machine_code_translator
description: "Professional, humanized Machine Code Translator with animations and dark theme"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_animate: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"